# Generated by Django 4.2.3 on 2023-09-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_vendor_identity_alter_vendor_profile_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
